server:
  port: 8081

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    username: root
    password: djPolina
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
timing:
    updateData: 5000

indexing-settings:
  sites:
    - url: https://www.svetlovka.ru/
      name: svetlovka.ru
    - url: https://playback.ru/
      name: playback.ru

jsoup-connection:
  user-agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2049.0 Safari/537.36
  referrer: http://www.google.com

params-query:
  percentLemma: 80.0f